---
el:
  hosts:
    centos7:
      ansible_connection: docker
      ansible_container: centos7
deb:
  hosts:
    ubuntu:
      ansible_connection: docker
      ansible_container: ubuntu
      ansible_python_interpreter: /usr/bin/python3
local:
  hosts:
    localhost:
      ansible_connection: local
fedora:
  hosts:
    fedora:
      ansible_connection: docker
      ansible_container: fedora
      ansible_python_interpreter: /usr/bin/python3
