version: "2.4"

services:
  centos7:
    image: centos:7
    container_name: centos7
    command: tail -f /dev/null
    tty: true

  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu
    command: tail -f /dev/null
    tty: true

