---
some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64306661373761396134336134306632383764623161383866623063636462386662303437373161
          6432616332306139393836373236323261356530353138300a323839366438313831373532376233
          31653736633161656237633366333336633862376535366338326534656563336339353437633232
          6361393062666265330a323464353364353238326566353363373365663030646631303730626339
          6165
